import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import ToastProvider from "@/components/layout/ToastProvider";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata = {
  title: "Qurbanirhat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto.className} h-full antialiased`}
    >
      <body>
        <Navbar />
        <main className="grow">{children}</main>
        <Footer />
        <ToastProvider />
      </body>

    </html>
  );
}
